#!/bin/sh

if [ $# -ne 3 ]; then
	echo "Usage: $0 owner name version" >&2
	exit 1
fi

OWNER=$1 NAME=$2 VERSION=$3

: ${JET_ROOT:=/jet}
: ${DOWNLOAD_URL:="https://jetware.io/appliances/$OWNER/$NAME-$VERSION/download/installer:nub_tgz"}
: ${PACKAGER_URL_PREFIX:='http://download.jetware.org/packager/'}
: ${DESTDIR:=$JET_ROOT}
: ${JET_USER:=jet}

download() {
	echo "${1%%*/}" >&2;
	wget -q -O - "$1";
}


mkdir -p "$DESTDIR"
download "$DOWNLOAD_URL" | tar xpzf - -C "$DESTDIR" || exit

while read PACKAGE ROLE NAME VERSION; do
	[ -e "$DESTDIR/use/$ROLE" ] && continue
	[ -h "$DESTDIR/use/$ROLE" ] && rm -f "$DESTDIR/use/$ROLE"
	mkdir "$DESTDIR/use/$ROLE"
	download "$PACKAGER_URL_PREFIX/$PACKAGE.tgz" | tar xpzf - -C "$DESTDIR/use/$ROLE" || exit
done < "$DESTDIR/own/packages"

"$DESTDIR"/own/bin/run "$JET_ROOT"/own/bin/config \
	appliance.author="$OWNER" \
	appliance.name="$NAME" \
	appliance.title="$NAME" \
	appliance.version="$VERSION" \
	appliance.url="https://jetware.io/appliances/$OWNER/$NAME-$VERSION" \
	appliance.support_url="https://jetware.io/contacts/submit?contacts_form%5Bsubject%5D=Appliance%3A+${OWNER}%2F${NAME}-${VERSION}"
