#!/bin/sh

set -x

while read os os_title; do
	read setuid_files < build-common/fixes/setuid.$os
	read setgid_files < build-common/fixes/setgid.$os
	docker pull jetware/base_os:$os
	docker build -t "build:$os" - <<_EOF_
FROM jet
RUN rm -rf /etc; rm -rf /bin /lib /sbin /tmp /usr /var
COPY --from=jetware/base_os:$os / /
RUN { chmod u+s $setuid_files; chmod g+s $setgid_files; true; } >/dev/null 2>&1
$(
docker image inspect --format '{{range $index, $element := .Config.Labels}}{{println $index $element}}{{end}}' jetware/base_os:$os | while read key value; do
	case $key in
	org.jetware.*) echo "LABEL \"$key\"=\"$value\"" ;;
	esac
done
)

RUN { echo "jet ALL=NOPASSWD: ALL"; echo "Defaults:jet !requiretty"; } > /etc/sudoers.d/99-jet-tmp && \
	{ echo "/jet/own/bin/run /jet/own/bin/fasten" | su jet -s /bin/sh ;} && \
	rm -f /etc/sudoers.d/99-jet-tmp

WORKDIR /jet
USER jet
VOLUME ["/jet/prs"]
ENTRYPOINT ["/jet/login"]
CMD ["main"]
_EOF_

done < operating_systems
