#!/bin/sh

set -x

[ -r docker_repo ] && read DOCKER_REPO < docker_repo

user=${DOCKER_REPO%/*}
repository=${DOCKER_REPO#*/}

if [ -e README.md -a ! -e README.md.src ]; then
	mv README.md README.md.src
fi

[ -e README.md.src ] && while IFS= read line; do
	case "$line" in
	@actual_tags@)
		build-common/print_actual_tags "$user" "$repository"
		;;
	*)
		printf "%s\n" "$line"
	esac
done < README.md.src > README.md

