#!/bin/sh

# Build a Docker image containing a jet pointed by GIT_TAG as ab-$OWNER/$NAME-$VERSION

set -x

appliance=${GIT_BRANCH#ab-}

# DOCKER_LOGIN can store arguments for the 'docker login' command, which include a password.
# Check the variable and do login in a subshell with the debugging off, and unset the variable
# later to prevent the leakage of a password.
(
set +x
if [ -n "$DOCKER_LOGIN" ]; then
		docker login $DOCKER_LOGIN
fi
) || exit
unset DOCKER_LOGIN

owner=${appliance%/*}
appliance=${appliance#*/}
name=${appliance%-*}
version=${appliance#*-}

# Build an image
docker build -t jet-fetch --build-arg=http_proxy=$http_proxy --build-arg=OWNER=$owner --build-arg=NAME=$name --build-arg=VERSION=$version build-common/fetch || exit

# Get a packages list
docker run --rm jet-fetch cat /jet/own/packages > packages

# Get a roles list to disclose
if ! [ -e disclose ]; then
	docker run --rm -i jet-fetch sh <<'_EOF_' > disclose
read roles < /jet/own/env/oneclickstack/principal
for role in $roles; do echo "$role"; done
read roles < /jet/own/env/oneclickstack/important
for role in $roles; do echo "$role"; done
_EOF_
	[ -s disclose ] || rm disclose
fi

disclose=
if [ -r disclose ]; then
	while read ROLE; do
		disclose="$disclose $ROLE"
	done < disclose
elif [ -r base_name_template ]; then
	read base_name_template < base_name_template
	name=${base_name_template%:*}
	[ "$name" = "$base_name_template" ] && tag= || tag=${base_name_template#*:}
	IFS=-
	for part in $name $tag; do
		disclose="$disclose $part"
	done
	unset IFS
fi

# Add labels for the packages
[ -n "$disclose" -a -r packages ] && while read  PACKAGE ROLE NAME VERSION; do
	case " $disclose " in
	*\ $ROLE\ *)
		eval name_$ROLE=\"\$NAME\"
		eval version_$ROLE=\"\$VERSION\"
		;;
	esac
done < packages

{
	echo "FROM jet-fetch"
	echo "LABEL maintainer=\"Jetware <dockerhub@jetware.org>\" \\"
	for ROLE in $disclose; do
		eval NAME=\"\$name_$ROLE\"
		[ -n "$NAME" ] || continue
		eval VERSION=\"\$version_$ROLE\"
		VERSION=${VERSION%%-jet-*}
		echo "  org.jetware.pkg.$ROLE=\"$NAME\" \"org.jetware.pkg.$ROLE.version\"=\"$VERSION\" \\"
	done
	echo "  org.jetware.appliance.url=\"http://jetware.org/appliances/$owner/$name-$version\" org.jetware.appliance.owner=\"$owner\" org.jetware.appliance.name=\"$name\" org.jetware.appliance.version=\"$version\" \\"
	echo "  org.label-schema.schema-version=\"1.0\" org.label-schema.vendor=\"Jetware/$owner\" org.label-schema.name=\"$name\" org.label-schema.version=\"$version\" org.label-schema.url=\"http://jetware.org/appliances/$owner/$name-$version\""
} | docker build -t jet -
