#!/bin/sh

set -x

read oses < operating_systems
read base_name_template < base_name_template

base_name=$(build-common/base_name $base_name_template `cat subtag_sources` < packages)

[ -n "$base_name" ] || { echo "No base_name" >&2; exit 1; }

for os in $oses; do
	tags=$(tags-generator/generate_tag_variants $base_name-$os subtags/*)
	[ -n "$tags" ] || { echo "No tags" >&2; exit 1; }
	for tag in $tags; do
		docker tag build:$os $DOCKER_REPO:$tag && docker push $DOCKER_REPO:$tag || exit
	done
done
